stages:
  - convert
  - generate
  - publish

convert_slides:
  image: registry.gitlab.com/gbraad/libreoffice:latest
  stage: convert
  script:
    - mkdir -p public
    - cp slides.odp public
    - libreoffice --headless --convert-to pdf --outdir public slides.odp
  artifacts:
    paths:
      - public
  only:
    - master

generate_index:
  image: registry.gitlab.com/gbraad/docugen:latest
  stage: generate
  script:
    - git clone https://gitlab.com/gbraad/document-generation-assets.git assets --depth 1
    - mkdir -p public
    - cp -r assets/public-content/reveal/* public/
    - pandoc -t html5 --template assets/templates/reveal-slides-template.html --standalone --section-divs ./index.md -o ./public/index.html
    - cp -r img public/
  artifacts:
    paths:
      - public
  only:
    - master

pages:
  image: registry.gitlab.com/gbraad/docker:git
  stage: publish
  artifacts:
    paths:
      - public
  only:
    - master
